apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partner-bevel-ac-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-bevel-ac-auth-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-auth-job
    sourceRef:
      kind: GitRepository
      name: flux-indy
      namespace: flux-indy
  values:
    metadata:
      name: partner-bevel-ac-auth-job
      namespace: partner-ns
    network:
      name: bevel
      kubernetes_url: https://359C9BD641315D040D39619F0F6E7FBE.yl4.us-east-1.eks.amazonaws.com
    image:
      name: partner
      repository: alpine:3.9.4
      pullPolicy: IfNotPresent
    vault:
      address: http://vault.default.svc.cluster.local:8200
      identity: bevel-ac
      admin_auth_path: kubernetes-partner-admin-auth
      policy: partner-bevel-ac-ro
      policy_content: path \"/*\" { capabilities = [ \"create\", \"read\", \"list\", \"update\", \"delete\", \"sudo\"] }
      auth_path: kubernetes-partner-bevel-ac-auth
    account:
      admin_service: partner-admin-vault-auth
      admin_role: rw
      service: partner-bevel-ac-vault-auth
      role: ro
