apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-endorser-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: partner-partner-endorser-auth-job
      namespace: partner-ns
    network:
      name: bevel
      kubernetes_url: https://7BFF136917E31CB861460C83A664A428.gr7.us-east-1.eks.amazonaws.com
    image:
      name: partner
      repository: alpine:3.9.4
    vault:
      address: http://a3df18bb47e8f41efb54e34322f59de4-825182735.us-east-1.elb.amazonaws.com:8200
      identity: partner-endorser
      admin_auth_path: kubernetes-partner-admin-auth
      policy: partner-partner-endorser-ro
      policy_content: path \"/partner/data/endorsers/partner-endorser/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-partner-partner-endorser-auth
    account:
      admin_service: partner-admin-vault-auth
      admin_role: rw
      service: partner-partner-endorser-vault-auth
      role: ro
