apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: partner-dtg
      namespace: partner-ns
    organization:
      name: partner
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"QWvaEMxLgxN1Ev8LHfsdcQ","role":"0","verkey":"DpPKLGNzhvU8wwPkD2KHhHYRTihmuDUtnwtRKetpAksC"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"2FicwzZLLeBEmKE4H8qXNk","role":"0","verkey":"gdkH2U1BXtiMqEyvUjLFUd66eVrgRP3HWXSjV8bqXhD"},"metadata":{"from":"QWvaEMxLgxN1Ev8LHfsdcQ"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"MUbn474DLj2zsECFkqSR3D","role":"2","verkey":"CAHN9Q99yhG8a9AnLkuVF99G2ZN8Sd8gUNDVfVwhfjo5"},"metadata":{"from":"2FicwzZLLeBEmKE4H8qXNk"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"MjxXkFj23GCLXtvBdKBUPc","role":"2","verkey":"CJercZTJugEFpJaYQLR48NWx987PVebP7s5BxWLeFNUQ"},"metadata":{"from":"2FicwzZLLeBEmKE4H8qXNk"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"YUpXQuuTspFeCivcx3HZ4W","role":"0","verkey":"JA8kWZTvqcwaf7CA2UvxLbxBxDXrDwH5edn9yp1gRJKd"},"metadata":{"from":"QWvaEMxLgxN1Ev8LHfsdcQ"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"8eKSf7RYe4pfJvNWg1LivP","role":"2","verkey":"5Ad9zZ1U61cR8r8GTvqoHD9wW6CspDmjWB2s5v43EWmM"},"metadata":{"from":"YUpXQuuTspFeCivcx3HZ4W"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"XBobNaTFta879iuZg8gWFe","role":"2","verkey":"HTFLyrrdFet33fourwrzJkzKPPi5pbqQHLJK9n4g9NLb"},"metadata":{"from":"YUpXQuuTspFeCivcx3HZ4W"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
