apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: provider-provider-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-endorser
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: provider-provider-endorser
      namespace: provider-ns
    network:
      name: bevel
    image:
      name: provider
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://a8e3897e42af646b49faf25942669568-584313495.us-east-1.elb.amazonaws.com:8200
      version: "2"
      keyPath: provider.endorsers
      identity: provider-endorser
      auth_path: kubernetes-provider-admin-auth
    account:
      service: provider-admin-vault-auth
      role: rw
