apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: provider-provider-steward-1
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-steward-1
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: provider-provider-steward-1
      namespace: provider-ns
    network:
      name: bevel
    image:
      name: provider
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://a3df18bb47e8f41efb54e34322f59de4-825182735.us-east-1.elb.amazonaws.com:8200
      version: "2"
      keyPath: provider.stewards
      identity: provider-steward-1
      auth_path: kubernetes-provider-admin-auth
    account:
      service: provider-admin-vault-auth
      role: rw
