apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-authority-trustee
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-authority-trustee
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: authority-authority-trustee
      namespace: authority-ns
    network:
      name: bevel
    image:
      name: authority
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://a3df18bb47e8f41efb54e34322f59de4-825182735.us-east-1.elb.amazonaws.com:8200
      version: "2"
      keyPath: authority.trustees
      identity: authority-trustee
      auth_path: kubernetes-authority-admin-auth
    account:
      service: authority-admin-vault-auth
      role: rw
