apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: partner-partner-endorser-transaction
      namespace: partner-ns
    network:
      name: bevel
    image:
      cli:
        name: partner
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://a3df18bb47e8f41efb54e34322f59de4-825182735.us-east-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: partner-admin-vault-auth
      auth_path: kubernetes-partner-admin-auth
    organization:
      name: partner
      adminIdentity:
        name: authority-trustee
        did: FcYkor6phbQeMzA6NQ4uBd
        path: authority/data/trustees
      newIdentity:
        name: partner-endorser
        role: ENDORSER
        did: NfiTDzAeAkHiDLV8DFDk3W
        verkey: CoxEGy8vUcfR7EprNPdSi62ZQ2RN92jNVfNu7fht6m8f
        path: partner/data/endorsers
    node:
      name: partner
