apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/sauveer/bevel.git
    ref: main
  values:
    metadata:
      name: partner-partner-endorser-transaction
      namespace: partner-ns
    network:
      name: bevel
    image:
      cli:
        name: partner
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://a8e3897e42af646b49faf25942669568-584313495.us-east-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: partner-admin-vault-auth
      auth_path: kubernetes-partner-admin-auth
    organization:
      name: partner
      adminIdentity:
        name: authority-trustee
        did: QWvaEMxLgxN1Ev8LHfsdcQ
        path: authority/data/trustees
      newIdentity:
        name: partner-endorser
        role: ENDORSER
        did: F19VDb8BkZdTzqHEsLFGR8
        verkey: 8deYgQdr9Bhi76Wc928MqAbwMwRm9GsRByYaJ4p2JjG3
        path: partner/data/endorsers
    node:
      name: partner
