apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partner-ptg
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-ptg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-pool-genesis
    sourceRef:
      kind: GitRepository
      name: flux-indy
      namespace: flux-indy
  values:
    metadata:
      name: partner-ptg
      namespace: partner-ns
    organization:
      name: partner
    configmap:
      poolGenesis: |-
        {"reqSignature":{},"txn":{"data":{"data":{"alias":"provider-steward-1","blskey":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","blskey_pop":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","client_ip":"34.193.94.87","client_port":9712,"node_ip":"34.193.94.87","node_port":9711,"services":["VALIDATOR"]},"dest":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"metadata":{"from":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"917292505e1e4063b0e6b30d73c131649e5a16271d3c96c3284751a66ef1ff50"},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"data":{"alias":"provider-steward-2","blskey":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","blskey_pop":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","client_ip":"34.193.94.87","client_port":9722,"node_ip":"34.193.94.87","node_port":9721,"services":["VALIDATOR"]},"dest":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"metadata":{"from":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"aecd2adbe0d6c4c0ef6e3f78503bddfa8e6078f030381ae895bae9d0da84124f"},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"data":{"alias":"partner-steward-1","blskey":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","blskey_pop":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","client_ip":"34.193.94.87","client_port":9732,"node_ip":"34.193.94.87","node_port":9731,"services":["VALIDATOR"]},"dest":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"metadata":{"from":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"62a426a55142745dcd68456212d322c8b63682274fcdffd10c3d274e0f87469b"},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"data":{"alias":"partner-steward-2","blskey":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","blskey_pop":"{
         \"errors\": [
         \"permission denied\"
         ]
        }","client_ip":"34.193.94.87","client_port":9742,"node_ip":"34.193.94.87","node_port":9741,"services":["VALIDATOR"]},"dest":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"metadata":{"from":"{
         \"errors\": [
         \"permission denied\"
         ]
        }"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"bf525e539b7e0d3e0eeeb2a075198dde681f56ce7d724aca0ebf6d606289a523"},"ver":"1"}
